name: Build and deploy to Docker Hub and EC2

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: zafar8588/devflow:${{ github.run_number }}

      - name: Verify Pushed Image
        run: docker pull zafar8588/devflow:${{ github.run_number }}

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            IMAGE_TAG=${{ github.run_number }}
            # Stop and remove the running container
            sudo docker stop codeflow || true
            sudo docker rm codeflow || true
            # Remove the previous image
            sudo docker rmi $(sudo docker images -q zafar8588/devflow:$IMAGE_TAG) || true
            # Pull the new image
            sudo docker pull zafar8588/devflow:$IMAGE_TAG
            # Run the new container
            sudo docker run -d --name codeflow -p 4000:4000 \
              --env-file /home/ubuntu/devflow/.env \
              zafar8588/devflow:$IMAGE_TAG
            # Check the running container
            sudo docker ps | grep codeflow
